### Google Home ###

# device ip address to speak
# ip_address: <string>
google_home_ip: "192.0.2.1"

### Mythings ###

# Secret
# secret: <string>
mythings_secret: ""

### HTTP Server ###

# UNIX domain socket http listening
# file path: <string>
# set `~` or `null` to disable.
socket_path: /var/run/gh-oshirase.sock

# TCP http listening
# port: <number>
# set `~` or `null` to disable.
tcp_port: ~

# TCP http listening hostname
# hostname: <string>
# set `~` or `null` to use "127.0.0.1".
tcp_hostname: ~
